image:
  file: .gitpod.Dockerfile

tasks:
  - name: root
    init: |
      cargo update
      cargo doc --all-features --workspace --no-deps
      cargo clippy --all-features --workspace --all-targets
      cargo test --all-features --workspace
    command: cargo watch -x 'test --all-features --workspace' -x 'clippy --all-features --all-targets --workspace' -x 'doc --all-features --workspace --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
