image:
  file: .gitpod.Dockerfile

tasks:
  - name: root
    init: |
      cargo update
      gp sync-done update
      cargo doc --all-features --no-deps
      cargo clippy --all-features --all-targets
      cargo test --all-features
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

  - name: core
    before: cd core
    init: |
      gp sync-await update
      cargo doc --all-features --no-deps
      cargo clippy --all-features --all-targets
      cargo test --all-features
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

  - name: debug
    before: cd debug
    init: |
      gp sync-await update
      cargo doc --all-features --no-deps
      cargo clippy --all-features --all-targets
      cargo test --all-features
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

  - name: macros
    before: cd macros
    init: |
      gp sync-await update
      cargo doc --all-features --no-deps
      cargo clippy --all-features --all-targets
      cargo test --all-features
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

  - name: rapier
    before: cd rapier
    init: |
      gp sync-await update
      cargo test --all-features
      cargo clippy --all-features --all-targets
      cargo doc --all-features --no-deps
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
