image:
  file: .gitpod.Dockerfile

tasks:
  - name: root
    init: |
      cp .cargo/fast_compiles_config .cargo/config.toml
      cargo update
      cargo doc --all-features --workspace --no-deps
      cargo clippy --all-features --workspace
      cargo test --all-features --workspace --tests
    command: cargo watch -x 'test --all-features --workspace --tests' -x 'clippy --all-features --workspace' -x 'doc --all-features --workspace --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
