[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0139", # ansi_term, used by bevy_log is unmaintained: https://github.com/ogham/rust-ansi-term/issues/72
]

[licenses]
default = "deny"
unlicensed = "deny"
copyleft = "deny"
allow = [
    "Unlicense",
    "MIT",
    "MIT-0",
    "BSD-3-Clause",
    "Apache-2.0",
    "Zlib",
    "ISC",
    "CC0-1.0",
    "Unicode-DFS-2016",
]

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "allow"
