version: 2.1

workflows:
  ci:
    jobs:
      - test-root
      - test-core
      - test-macros
      - test-rapier
      - test-debug

executors:
  rust:
    docker:
      - image: cimg/rust:1.60
      
jobs:
  test-root:
    executor: rust
    steps:
      - checkout
      - run: cargo update
      - restore_cache:
          key: cargo-root-{{ checksum "Cargo.lock" }}
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features collision-from-mesh
      - run: cargo test --no-default-features --features 2d
      - run: cargo test --no-default-features --features 3d
      - run: cargo test --no-default-features --features enhanced-determinism
      - run: cargo test --no-default-features --features debug-2d
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --all-features -- --ignored
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-root-{{ checksum "Cargo.lock" }}
  test-core:
    executor: rust
    steps:
      - checkout
      - run: cargo update
      - restore_cache:
          key: cargo-core-{{ checksum "Cargo.lock" }}
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features collision-from-mesh
      - run: cargo test --no-default-features --features 3d
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --all-features -- --ignored
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-core-{{ checksum "Cargo.lock" }}
  test-macros:
    executor: rust
    steps:
      - checkout
      - run: cargo update
      - restore_cache:
          key: cargo-macros-{{ checksum "Cargo.lock" }}
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --all-features -- --ignored
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-macros-{{ checksum "Cargo.lock" }}
  test-rapier:
    executor: rust
    steps:
      - checkout
      - run: cargo update
      - restore_cache:
          key: cargo-rapier-{{ checksum "Cargo.lock" }}
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features 2d
      - run: cargo test --no-default-features --features 3d
      - run: cargo test --no-default-features --features enhanced-determinism
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --all-features -- --ignored
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-rapier-{{ checksum "Cargo.lock" }}
  test-debug:
    executor: rust
    steps:
      - checkout
      - run: cargo update
      - restore_cache:
          key: cargo-debug{{ checksum "Cargo.lock" }}
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features 2d
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --all-features -- --ignored
      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-debug-{{ checksum "Cargo.lock" }}
