version: 2.1

workflows:
  ci:
    jobs:
      - test
      - code-style

executors:
  rust:
    docker:
      - image: cimg/rust:1.60
      
jobs:
  test:
    executor: rust
    steps:
      - checkout
      - run: cargo test --workspace --no-default-features
      - run: cargo test --workspace --no-default-features --features collision-from-mesh
      - run: cargo test --workspace --no-default-features --features 2d
      - run: cargo test --workspace --no-default-features --features 3d
      - run: cargo test --workspace --no-default-features --features enhanced-determinism
      - run: cargo test --workspace --no-default-features --features debug-2d
      - run: cargo test --workspace 
      - run: cargo test --workspace --all-features
      - run: cargo test --workspace --all-features -- --ignored
      - run: cargo doc --workspace --all-features --no-deps
  code-style:
    executor: rust
    steps:
      - checkout
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --workspace
