version: 2.1

workflows:
  ci:
    jobs:
      - test-no-feature
      - test-all-features
      - test-2d
      - test-3d
      - test-enhanced-determinism
      - test-debug-2d
      - documentation
      - code-style

executors:
  rust:
    docker:
      - image: cimg/rust:1.60
      
jobs:
  test-no-feature:
    executor: rust
    steps:
      - checkout
      - run: cargo test --workspace --no-default-features
      - run: cargo test --workspace
  test-all-features:
    executor: rust
    steps:
      - checkout
      - run: cargo test --workspace --all-features
      - run: cargo test --workspace --all-features -- --ignored
  test-2d:
    executor: rust
    steps:
      - checkout
      - run: cargo test -p heron_rapier --no-default-features --features 2d
      - run: cargo test -p heron_debug --no-default-features --features 2d
      - run: cargo test --no-default-features --features 2d
  test-3d:
    executor: rust
    steps:
      - checkout
      - run: cargo test -p heron_core --no-default-features --features 3d
      - run: cargo test -p heron_rapier --no-default-features --features 3d
      - run: cargo test --no-default-features --features 3d
  test-enhanced-determinism:
    executor: rust
    steps:
      - checkout
      - run: cargo test -p heron_rapier --no-default-features --features enhanced-determinism
      - run: cargo test --no-default-features --features enhanced-determinism
  test-debug-2d:
    executor: rust
    steps:
      - checkout
      - run: cargo test --no-default-features --features debug-2d
  documentation:
    executor: rust
    steps:
      - checkout
      - run: cargo doc --workspace --all-features --no-deps
  code-style:
    executor: rust
    steps:
      - checkout
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --workspace
