name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: Release level
        required: true

jobs:
  release:
    needs: verify
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: '1.56.0'
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - run: cargo test --workspace --all-features
      - run: cargo test --workspace --features 2d
      - run: cargo test --workspace --features 3d
      - run: cargo test --workspace --features debug-2d
      - run: cargo doc --workspace --all-features

      - name: Install cargo-release
        run: cargo install cargo-release --version 0.18.2

      - name: Configure git user
        run: |
          git config --global user.name "Jonathan Cornaz"
          git config --global user.email "jcornaz@users.noreply.github.com"

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_TOKEN }}

      - name: Release
        run: cargo release ${{ github.event.inputs.level }} --no-confirm --workspace --execute

      - run: git push
      - run: git push --tags
